export const GITHUB_PROFILE_REQUEST = 'GITHUB_PROFILE_REQUEST';
export const GITHUB_PROFILE_SUCCESS = 'GITHUB_PROFILE_SUCCESS';
export const GITHUB_PROFILE_FAILED = 'GITHUB_PROFILE_FAILED';
export const GMAPS_GEOLOCATION_GIT_REQUEST = 'GMAPS_GEOLOCATION_GIT_REQUEST';
export const GMAPS_GEOLOCATION_GIT_SUCCESS = 'GMAPS_GEOLOCATION_GIT_SUCCESS';
export const GMAPS_GEOLOCATION_GIT_FAILED = 'GMAPS_GEOLOCATION_GIT_FAILED';
